<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
use Magento\Framework\App\ActionInterface;

/** @var \Aheadworks\Wbtab\Block\Wbtab\ProductList $block */
$items = $block->getItems();
if (count($items) > 0):
    $class = 'aw_wbtab';
    $image = 'related_products_list';

    $title = $block->getBlockTitle();
    $showCart =  $block->getDisplayAddToCart();
    $dataMageInit = $block->getDataMageInit();
    $delivery= $this->helper('Boostsales\Delivering\Helper\Delivery');
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
    $FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey'); 
?>

    <div data-mage-init='<?php /* @noEscape */ echo $dataMageInit ?>' class="block <?php /* @noEscape */ echo $class; ?>" >
        <div class="block-title title">
            <strong id="block-<?php /* @noEscape */ echo $class?>-heading" role="heading" aria-level="2"><?php echo $block->escapeHtml($title); ?></strong>
        </div>
        <div class="block-content content" aria-labelledby="block-<?php /* @noEscape */ echo $class?>-heading">
            <div class="products wrapper grid products-grid products-<?php /* @noEscape */ echo $class; ?>">
                <ol data-aw-wbtab-block="items" class="products list items product-items">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php $available = ''; ?>

                        <?php if (!$_item->isComposite() && $_item->isSaleable()): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php /* @noEscape */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>

                        <div class="product-item-info <?php /* @noEscape */ echo $available; ?>">
                            <?php /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
                            <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                </strong>
                                <?php echo $delivery->getDeliveryHtml($_item->getId()); ?> 
                                <?php /* @noEscape */ echo $block->getProductPrice($_item); ?>
                                <?php if ($showCart): ?>
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()): ?>
                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @noEscape */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php echo $block->escapeHtml(__('Add to Cart')) ?>">
                                                            <span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            <?php else: ?>
                                                <?php
                                                $postData = json_decode($block->getPostDataHelper()
                                                    ->getPostData(
                                                        $block->getAddToCartUrl($_item),
                                                        ['product' => $_item->getEntityId()]
                                                    ),true);
                                                $value = $postData['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?> method="post">
                                                    <input type="hidden" name="product" value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>">
                                                    <input type="hidden" name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED?>" value="<?= /* @noEscape */ $value ?>">
                                                    <input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
                                                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart primary">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>

<?php endif;?>
<script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_item->getSku() ?>"
                }
            }
        }
</script>
