<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php
    $helperDesign = $this->helper('Infortis\Base\Helper\Design');
    $currentFlagUrl = $helperDesign->getFlagUrl($block->getCurrentStoreCode());    
?>
<?php if (count($block->getGroups())>1): ?>
<div class="switcher store switcher-store" id="switcher-store">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Select Store')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <?php foreach ($block->getGroups() as $_group): ?>
        <?php if ($_group->getId() == $block->getCurrentGroupId()): ?>
            <div class="action toggle switcher-trigger"
                 role="button"
                 tabindex="0"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true"
                 id="switcher-store-trigger">
                 <img class="store-flag-icon" src="<?= $currentFlagUrl ?>" alt="<?= $block->getStoreName() ?>"> 
                <strong>
                    <span><?= $block->escapeHtml($_group->getName()) ?></span>
                </strong>
            </div>
        <?php endif; ?>
        <?php endforeach; ?>
        <ul class="dropdown switcher-dropdown" data-target="dropdown">
            <?php foreach ($block->getGroups() as $_group): ?>
            <?php if (!($_group->getId() == $block->getCurrentGroupId())): ?>
                <?php $getStoreCode = $_group->getStoreCodes(); ?>
                <li class="switcher-option">
                    <a href="#" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_group->getDefaultStore()) ?>'>
                        <span class="label"><?php echo $block->escapeHtml($block->getStoreName()) ?></span><?= $block->escapeHtml($_group->getName()) ?>
                        <img class="store-switcher-icon" src="<?= $helperDesign->getFlagUrl($getStoreCode[key($_group->getStoreCodes())]) ?>" alt="<?= $getStoreCode[key($_group->getStoreCodes())] ?>"/>
                    </a>
                </li>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
