<style>
    .email-items .order-body td,
    .email-items .order-totals th,
    .email-items .order-totals td{
        font-family: Arial !important;
    }
</style>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $delivery= $this->helper('Boostsales\Delivering\Helper\Delivery'); ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order) : ?>
<?php $_items = $_order->getAllItems(); ?>
<table class="email-items">
    <thead>
        <tr>
            <th class="item-info" style="text-transform: capitalize; font-family: Arial;">
                <?= $block->escapeHtml(__('Items')) ?>
            </th>
            <th class="item-qty" style="text-transform: capitalize; font-family: Arial;">
                <?= $block->escapeHtml(__('Qty')) ?>
            </th>
            <th class="item-price" style="text-transform: capitalize; font-family: Arial;">
                <?= $block->escapeHtml(__('Price')) ?>
            </th>
        </tr>
    </thead>
    <?php
        $currentId = 0;
        $productId = null;
    ?>
    <?php foreach ($_items as $_item) : ?>
    <?php if (!$_item->getParentItem()) : ?>
    <tbody class="order-body" style="font-family: Arial !important;">
        <?= $block->getItemHtml($_item) ?>
    </tbody>
    <?php
        $productId = $_item->getProductId();
        $delayId = $delivery->getDeliveryDelayId($productId);
        if(isset($delayId['id']) && $delayId['id'] > $currentId){
            $currentId = $delayId['id'];
            $productIdDelayId = $productId;
            $delayMsg = $delayId['message'];
        }
    ?>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php if(isset($delayId['message']) && isset($delayId['id']) == false ){
        $inStockMsg = $delayId['message'];
    }else {
        $inStockMsg = $block->escapeHtml(__("Delivery as discussed"));
    }
    ?>
    <tfoot class="order-totals" style="font-family: Arial !important;">
        <?= $block->getChildHtml('order_totals') ?>
    </tfoot>
</table>
<br />
<table>
    <tr>
        <td style="padding-bottom: 5px; width: 135px;">
            <b style=" font-family: Arial;"><?= $block->escapeHtml(__('Levertijd')) ?></b>
        </td>
        <td style="font-size: 13px; color: #000; font-family: Arial;">
            <?php echo isset($delayMsg) ? $delayMsg : $inStockMsg ?>
        </td>
    </tr>
    <tr>
        <td style="padding-bottom: 5px; width: 135px;">
            <b style=" font-family: Arial;"><?= $block->escapeHtml(__('Verzendmethode')) ?></b>
        </td>
        <td style="font-size: 13px; color: #000; font-family: Arial;">
            <?php echo $_order->getShippingDescription();?>
        </td>
    </tr>
    <tr>
        <td style="padding-bottom: 5px; width: 135px;">
            <b style=" font-family: Arial;"><?= $block->escapeHtml(__('Betaalmethode')) ?></b>
        </td>
        <td style="font-size: 13px; color: #000; font-family: Arial;">
            <?= $block->escapeHtml($_order->getPayment()->getMethodInstance()->getTitle());?>
        </td>
    </tr>
    <tr>
        <td style="width: 135px;">
            <b style=" font-family: Arial;"><?= $block->escapeHtml(__('Uw inkoopnummer')) ?></b>
        </td>
        <?php if(isset($_order->getData()['po_number'])) :?>
            <td style="font-size: 13px; color: #000;font-family: Arial;">
                <?php echo $_order->getData()['po_number']; ?>
            </td>
        <?php elseif($_order->getEmailCustomerNote() != NULL):?>
            <td style="font-size: 13px; color: #000;font-family: Arial;">
                <?php echo $_order->getEmailCustomerNote(); ?>
            </td>
        <?php endif;?>
    </tr>
</table>
<br />
<?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
->isMessagesAllowed('order', $_order, $_order->getStore())
&& $_order->getGiftMessageId()
) : ?>
<?php $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
->getGiftMessage($_order->getGiftMessageId()); ?>
<?php if ($_giftMessage) : ?>
<br />
<table class="message-gift">
    <tr>
        <td style="font-family: Arial;">
            <h3 style="font-family: Arial; font-size: 18px;color: #000; margin-bottom: 8px;"><?= $block->escapeHtml(__('Gift Message for this Order')) ?></h3>
            <strong style=" font-family: Arial;"><?= $block->escapeHtml(__('From:')) ?></strong>
            <?= $block->escapeHtml($_giftMessage->getSender()) ?>
            <br /><strong style=" font-family: Arial;"><?= $block->escapeHtml(__('To:')) ?></strong>
            <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
            <br /><strong style=" font-family: Arial;"><?= $block->escapeHtml(__('Message:')) ?></strong>
            <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
        </td>
    </tr>
</table>
<?php endif; ?>
<?php endif; ?>
<?php endif; ?>
