<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage */
?>
<?php
$deliveryHelper = $this->helper('Boostsales\Delivering\Helper\Delivery');
$websiteId = $deliveryHelper->getStore()->getWebsiteId();
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        webstoreId = <?= $websiteId ?>;
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>");
            return url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
        })
    </script>
    <script>
      require(['jquery', 'checkoutStepTwo'], function($, checkoutStepTwo){
        checkoutStepTwo();
        $(document).ready(function(){
            if(webstoreId == 3){
                var invoiceEmailIntl = setInterval(() => {
                    var invoiceEmail = $('#opc-custom-invoice-email');
                    if(invoiceEmail.length > 0){
                        $('#opc-custom-invoice-email .invoice-field').css('display','none');
                        clearInterval(invoiceEmailIntl);
                    }
                }, 400);
            }
        });
      })
    </script>
</div>
<!-- <div id="euvatResponseModal">
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nemo dolor dolores, possimus.</p>
</div> -->