<?php
    $theme = $this->helper('Infortis\Base\Helper\Data');
    $accountLinksHtml = '';

    //Default Magento Top Links
    if ($theme->getCfg('header/top_links'))
    {
        $accountLinksHtml .= $block->getChildHtml('top.links');
    }

    //Additional custom links
    if ($tmpHtml = $block->getChildHtml('block_header_top_links'))
    {
        $accountLinksHtml .= $tmpHtml;
    }
?>
<?php
    $objectManagerlogin = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManagerlogin->get('Magento\Customer\Block\Account\Customer');
    $baseurl = $objectManagerlogin->get('Magento\Store\Model\StoreManagerInterface')->getStore(0)->getBaseUrl();
?>
<?php if ($accountLinksHtml && !$customerSession->customerLoggedIn()): ?>
    <div id="header-account" class="account-links top-links links-wrapper-separators-left skip-content skip-content--style">
        <?php echo $accountLinksHtml; ?>
    </div>
<?php elseif($customerSession->customerLoggedIn() && $accountLinksHtml):?>
    <div id="header-account" class="account-links top-links links-wrapper-separators-left skip-content skip-content--style">
        <?php echo $accountLinksHtml; ?>
    </div>
    <script>
        jQuery('.header.links .authorization-link').before("<li class='account-link'><a class='my-account' href=<?php echo $baseurl .'customer/account'; ?>><?= __('My Account')?></a></li>");
    </script>
<?php endif; ?>
