<?php
/**
 * @var \Fooman\PdfCustomiser\Block\Shipment $block
 *
 * Note on the use of @noEscape throughout this template
 * html output is allowed by design to allow users to customise their pdfs
 * Before pdf rendering all output is run filtered by @see \Magento\Framework\Filter\Input\MaliciousCode
 */
?>
<?php $shipment = $block->getShipment() ?>
<?php $order = $block->getOrder() ?>
<?php $design = $block->getDesign() ?>

<table width="100%" border="0" cellpadding="2" cellspacing="0">
<tr>
        <td width="50%" align="left">
            <?php $style = array(
                'border' => false,
                'hpadding' => 'auto',
                'vpadding' => 'auto',
                'fgcolor' => array(0,0,0),
                'bgcolor' => false, //array(255,255,255),
                'text' => false,
                'font' => 'helvetica',
                'fontsize' => 8,
                'stretchtext' => 4
            ); ?>
                <?php $barcodeParams = [
                    $order->getIncrementId(),
                    $block->getBarcodeType(),
                    //the parameters below refer to x, y, width, and height of the barcode respectively
                    '', '', '35', '8',
                    '', $style
                ]; ?>
                <tcpdf method="write1DBarcode" <?php echo $block->getEncodedParams($barcodeParams) ?>/>
        </td>
    </tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr>
        <?php if ($block->isLogoOnRight()): ?>
            <td valign="top"
                width="40%"
                height="30mm"
                style="font-weight:bold; font-size:<?= /* @noEscape */ $block->getFontsize('large') ?>"
            ></td>
            <td valign="top">&nbsp;<?= /* @noEscape */ $block->getLogoBlock() ?></td>
        <?php else: ?>
            <td width="40%"
                valign="top">&nbsp;<?= /* @noEscape */ $block->getLogoBlock() ?></td>
            <td valign="top"
                height="30mm"
                style="font-weight:bold;font-size:<?= /* @noEscape */ $block->getFontsize('large') ?>"
            ></td>
        <?php endif; ?>
    </tr>
    <tr>
        <td valign="top" width="50%"><span valign="top"
                height="30mm"
                style="font-weight:bold;font-size:<?= /* @noEscape */ $block->getFontsize('large') ?>"
            ><?= $block->escapeHtml($block->getTitle()) ?></span><br /><?= $block->escapeHtml(__('Packingslip #')) ?>:
            <?= $block->escapeHtml($shipment->getIncrementId()) ?><br/>
            <?php if ($block->showOrderIncrementId()): ?>
                <?= $block->escapeHtml(__('Order #') . ': ' . $order->getIncrementId()) ?><br/>
            <?php endif; ?>
            <?= $block->escapeHtml(__('Date')) ?>:
            <?= /* @noEscape */ $block->getFormattedDate($order->getCreatedAt()) ?><br/>
            <?= /* @noEscape */ $block->getCommentsBlock() ?>
            <?php if(isset(($order->getData()['po_number'])) && !empty($order->getData()['po_number'])) :?>
                <strong><?= $block->escapeHtml(__('Purchase Order Number')) ?><br /></strong>
                <?= $block->escapeHtml($order->getData()['po_number']); ?>
            <?php endif; ?>
        </td>
 <?php if ($block->shouldDisplayShippingAddress()): ?>
            <td valign="top" colspan="2"><?= /* @noEscape */ $block->getShippingAddress() ?></td>
        <?php elseif ($block->shouldDisplayBillingAddress()): ?>
            <td valign="top" colspan="2"><?= /* @noEscape */ $block->getBillingAddress() ?></td>
        <?php endif; ?>

</tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>

    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    <?php if ($order->getIsVirtual()): ?>
        <tr>
            <!-- <td valign="top" colspan="2"><strong><?php  //$block->escapeHtml(__('Payment Method')) ?></strong></td> -->
        </tr>
        <tr>
            <!-- <td valign="top" colspan="2"><?php /* @noEscape */ //nl2br//($block->getPaymentBlock()) ?></td> -->
        </tr>
    <?php else: ?>
        <tr>
            <td valign="top" width="50%"><strong><?php //$block->escapeHtml(__('Payment Method')) ?></strong></td>
            <td valign="top"><strong><?= $block->escapeHtml(__('Shipping Method')) ?></strong></td>
        </tr>
        <tr>
            <td valign="top" width="50%"><?php /* @noEscape */ //nl2br//(//$block->getPaymentBlock()) ?></td>
            <td valign="top"><?= /* @noEscape */ $block->getShippingBlock() ?></td>
        </tr>
    <?php endif; ?>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
</table>

<?= /* @noEscape */ $block->getItemsBlock($design->getItemStyling()) ?>


<?= /* @noEscape */ $block->getGiftmessageBlock()?>

<?php $customText = $block->getCustomText() ?>
<?php if ($customText): ?>
    <br/>
    <table width="100%" border="0" cellpadding="2" cellspacing="0">
        <tr>
            <td colspan="2"><?= /* @noEscape */ $customText ?></td>
        </tr>
    </table>
<?php endif; ?>

<?php $groupText = $block->getGroupText($order->getCustomerGroupId()) ?>
<?php if ($groupText): ?>
    <br/>
    <table width="100%" border="0" cellpadding="2" cellspacing="0">
        <tr>
            <td colspan="2"> <?= /* @noEscape */ $groupText ?></td>
        </tr>
    </table>
<?php endif; ?>
