<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Checkout\Block\Onepage\Success $block */
/** @var \Aheadworks\OrderSuccessPage\ViewModel\Checkout\Success\Text $viewModel */
$viewModel = $block->getViewModel();
$splitOrder = $block->getLayout()->createBlock('Boostsales\PartialShipment\Block\Checkout\Success');
$orderArray = $splitOrder->getOrderArray();
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<div class="checkout-success">
    <?php if ($viewModel->getSuccessPageText()): ?>
        <div class="aw_osp-success-text">
            <p><?= $block->escapeHtml($viewModel->getSuccessPageText()) ?></p>
        </div>
    <?php endif; ?>
    <?php if ($block->getOrderId()):?>
        <?php if ($orderArray):?>
            <p><?= /* @escapeNotVerified */ __('Your orders number are:');?></p>
            <ul>
            <?php foreach ($orderArray as $order => $incremental): ?>
                <?php if ($block->getCanViewOrder()) :?>
                    <li><?= sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $this->getUrl('sales/order/view/', ['order_id' => $order]), $block->escapeHtml($incremental)) ?></li>
                <?php else :?>
                    <li><?= $block->escapeHtml($incremental) ?></li>
                <?php endif;?>
            <?php endforeach; ?>
            </ul>
            <?php else: ?>
            <?php if ($block->getCanViewOrder()) :?>
                <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
            <?php  else :?>
                <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
            <?php endif;?>
            <?php if ($viewModel->isOrderEmailEnabled()): ?>
                <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
            <?php endif; ?>
        <?php endif;?>
    <?php endif;?>
    <?php $order = $splitOrder->getOrder($orderArray); ?>
    <h2> Backorder Details </h2>
    <div class="order-detail">
        <table>
            <thead>
                <tr>
                    <th class="col item"><?php /* @escapeNotVerified */ echo __('Product Name'); ?></th>
                    <th class="col item"><?php /* @escapeNotVerified */ echo __('SKU'); ?></th>
                    <th class="col price"><?php /* @escapeNotVerified */ echo __('Price'); ?></th>
                    <th class="col qty"><?php /* @escapeNotVerified */ echo __('Qty'); ?></th>
                    <th class="col subtotal"><?php /* @escapeNotVerified */ echo __('Subtotal'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($order->getAllVisibleItems() as $item) {
                    $product = $splitOrder->getItem($item->getProductId());
                    ?>
                    <tr class="data-item">
                        <td class="product-name"><span><?php echo $item->getName(); ?></span></td>
                        <td class="product-sku"><span><?php echo $item->getSku(); ?></span></td>
                        <td class="product-price"><?php echo $priceHelper->currency($item->getPrice(),true,false);?></td> 
                        <td class="product-qty"><?php echo $item->getQtyOrdered(); ?></td> 
                        <td class="product-subtotal"><?php echo $priceHelper->currency($item->getBaseRowTotal(),true,false);?></td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>
            <tfoot>
                <tr class="subtotal">
                    <th colspan="5" class="order-details-subtotal" scope="row">
                        <?php /* @escapeNotVerified */ echo __('Subtotal'); ?>
                    </th>
                    <td class="number" data-th="<?php /* @escapeNotVerified */ echo __('Subtotal'); ?>">
                        <span class="price"><?php echo $priceHelper->currency($order->getSubtotal(),true,false);?></span>                    
                    </td>
                </tr>
                <tr class="shipping">
                    <th colspan="5" class="order-details-shipping" scope="row">
                        <?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling'); ?>
                    </th>
                    <td class="number" data-th="<?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling'); ?>">
                        <span class="price"><?php echo $priceHelper->currency($order->getShippingAmount(),true,false); ?></span>                    
                    </td>
                </tr>
                <tr class="grand_total">
                    <th colspan="5" class="order-details-grandtotal" scope="row">
                        <strong><?php /* @escapeNotVerified */ echo __('Grand Total'); ?></strong>
                    </th>
                    <td class="number" data-th="<?php /* @escapeNotVerified */ echo __('Grand Total'); ?>">
                        <strong><span class="price"><?php echo $priceHelper->currency($order->getGrandTotal(),true,false); ?></span></strong>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <?= $block->getChildHtml('order.success.blocks') ?>
    <?= $block->getAdditionalInfoHtml() ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
