<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$orderObj = $objectManager->create('Magento\Checkout\Model\Session')->getLastRealOrder();
$payment = $orderObj->getPayment();
$method = $payment->getMethodInstance();
$methodCode = $method->getCode();

?>


<div class="success-order-aftersteps">
    <div class="section-heading">
        <h2 class="title"><?=__('Good to Know') ?> </h2>
    </div>
    <div class="section-body">
        <?php switch($methodCode): 
            case 'checkmo': ?>
                <div class="row-1 three-column">
                    <div class="col-1 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                            <div class="circle-icon-col-2">
                                <div class="icon-bar"></div>
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Bestelbevestiging') ?>
                        </div>
                        <div class="col-text">
                            <?= __('U ontvangt per e-mail een bestelbevestiging met alle informatie zoals levertijd, betaalmethode, etc.')?>
                        </div>
                    </div>
                    <div class="col-2 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                            <div class="circle-icon-col-2">
                                <div class="icon-bar"></div>
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Verzending') ?>
                        </div>
                        <div class="col-text">
                            <?= __('Zodra uw bestelling ingepakt is, sturen wij u direct een e-mail met alle Track & Trace informatie.')?>
                        </div>
                    </div>
                    <div class="col-3 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Factuur (Op rekening 30 dagen)') ?>
                        </div>
                        <div class="col-text">
                            <?= __('Nadat de (eerste) zending ons magazijn heeft verlaten, ontvangt u van de factuur. Op dit document kunt u alle informatie vinden zoals bankinformatie, Tarrif codes, land van herkomst, etc.')?>
                        </div>
                    </div>
                </div>
            <?php break; ?>
            <?php case 'banktransfer': ?>
                <div class="row-1 checkmo">
                    <div class="col-1 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                            <div class="circle-icon-col-2">
                                <div class="icon-bar"></div>
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Bestelbevestiging') ?>
                        </div>
                        <div class="col-text">
                            <?= __('U ontvangt per e-mail een bestelbevestiging met alle informatie zoals levertijd, betaalmethode, etc.')?>
                        </div>
                    </div>
                    <div class="col-2 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                            <div class="circle-icon-col-2">
                                <div class="icon-bar"></div>
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Proforma factuur') ?>
                        </div>
                        <div class="col-text">
                            <?= __('Voor we de bestelling verder kunnen verwerken, dient u eerste de bankoverschrijving te voldoen. Wij sturen u via e-mail een proforma factuur in PDF met alle benodigde informatie.')?>
                        </div>
                    </div>
                    <div class="col-3 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                            <div class="circle-icon-col-2">
                                <div class="icon-bar"></div>
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Uw factuur') ?>
                        </div>
                        <div class="col-text">
                            <?= __('De factuur wordt per e-mail verzonden. Bewaar deze goed dit is ook uw garantiebewijs.')?>
                        </div>
                    </div>
                    <div class="col-4 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                            <div class="circle-icon-col-2">
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Verzending')?>
                        </div>
                        <div class="col-text">
                            <?= __('Zodra uw bestelling ingepakt is, sturen wij u direct een e-mail met alle Track & Trace informatie.')?>
                        </div>
                    </div>
                </div>
            <?php break; ?>
            <?php default: ?>
                <div class="row-1 three-column">
                    <div class="col-1 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                            <div class="circle-icon-col-2">
                                <div class="icon-bar"></div>
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Bestelbevestiging') ?>
                        </div>
                        <div class="col-text">
                            <?= __('U ontvangt per e-mail een bestelbevestiging met alle informatie zoals levertijd, betaalmethode, etc.')?>
                        </div>
                    </div>
                    <div class="col-2 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                            <div class="circle-icon-col-2">
                                <div class="icon-bar"></div>
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Uw factuur') ?>
                        </div>
                        <div class="col-text">
                            <?= __('De factuur wordt per e-mail verzonden. Bewaar deze goed dit is ook uw garantiebewijs.')?>
                        </div>
                    </div>
                    <div class="col-3 col">
                        <div class="circle-icon-row">
                            <div class="circle-icon-col-1">
                                <div class="circle-icon"></div>
                            </div>
                        </div>
                        <div class="col-heading">
                            <?= __('Verzending') ?>
                        </div>
                        <div class="col-text">
                            <?= __('Zodra uw bestelling ingepakt is, sturen wij u direct een e-mail met alle Track & Trace informatie.')?>
                        </div>
                    </div>
                </div>
            <?php break; ?>
        <?php endswitch; ?>
    </div>
</div>