<?php

?>
<div class="success-order-aftersteps">
    <div class="section-heading">
        <h2 class="title">Good to Know</h2>
    </div>
    <div class="section-body">
        <div class="row-1">
            <div class="col-1 col">
                <div class="circle-icon-row">
                    <div class="circle-icon-col-1">
                        <div class="circle-icon"></div>
                    </div>
                    <div class="circle-icon-col-2">
                        <div class="icon-bar"></div>
                    </div>
                </div>
                <div class="col-heading">
                    Lorem Ipsum
                </div>
                <div class="col-text">
                    Reference site about Lorem Ipsum, giving information on its origin as well as random.
                </div>
            </div>
            <div class="col-2 col">
                <div class="circle-icon-row">
                    <div class="circle-icon-col-1">
                        <div class="circle-icon"></div>
                    </div>
                    <div class="circle-icon-col-2">
                        <div class="icon-bar"></div>
                    </div>
                </div>
                <div class="col-heading">
                    Lorem Ipsum
                </div>
                <div class="col-text">
                    Reference site about Lorem Ipsum, giving information on its origin as well as random.
                </div>
            </div>
            <div class="col-3 col">
                <div class="circle-icon-row">
                    <div class="circle-icon-col-1">
                        <div class="circle-icon"></div>
                    </div>
                    <div class="circle-icon-col-2">
                        <div class="icon-bar"></div>
                    </div>
                </div>
                <div class="col-heading">
                    Lorem Ipsum
                </div>
                <div class="col-text">
                    Reference site about Lorem Ipsum, giving information on its origin as well as random.
                </div>
            </div>
            <div class="col-4 col">
                <div class="circle-icon-row">
                    <div class="circle-icon-col-1">
                        <div class="circle-icon"></div>
                    </div>
                    <div class="circle-icon-col-2">
                    </div>
                </div>
                <div class="col-heading">
                    Lorem Ipsum
                </div>
                <div class="col-text">
                    Reference site about Lorem Ipsum, giving information on its origin as well as random.
                </div>
            </div>
        </div>
    </div>
</div>